-- Extend existing Notification model for operational notifications persistence
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'APPOINTMENT_CONFIRMED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'APPOINTMENT_NO_SHOW';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'SERVICE_ORDER_COMPLETED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'PAYMENT_OVERDUE';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'RISK_LEVEL_CHANGED';

ALTER TABLE "Notification"
ADD COLUMN IF NOT EXISTS "title" TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS "read" BOOLEAN NOT NULL DEFAULT false;
