export const AUDIT_ACTIONS = {
  // Service Orders
  SERVICE_ORDER_CREATED: 'SERVICE_ORDER_CREATED',
  SERVICE_ORDER_UPDATED: 'SERVICE_ORDER_UPDATED',
  SERVICE_ORDER_STATUS_CHANGED: 'SERVICE_ORDER_STATUS_CHANGED',
  SERVICE_ORDER_ASSIGNED_CHANGED: 'SERVICE_ORDER_ASSIGNED_CHANGED',

  // Customers
  CUSTOMER_CREATED: 'CUSTOMER_CREATED',
  CUSTOMER_UPDATED: 'CUSTOMER_UPDATED',
  CUSTOMER_ACTIVE_CHANGED: 'CUSTOMER_ACTIVE_CHANGED',

  // Appointments
  APPOINTMENT_CREATED: 'APPOINTMENT_CREATED',
  APPOINTMENT_UPDATED: 'APPOINTMENT_UPDATED',
  APPOINTMENT_STATUS_CHANGED: 'APPOINTMENT_STATUS_CHANGED',
  APPOINTMENT_CONFLICT_BLOCKED: 'APPOINTMENT_CONFLICT_BLOCKED',

  // Finance
  CHARGE_CREATED: 'CHARGE_CREATED',
  CHARGE_PAID: 'CHARGE_PAID',
  PAYMENT_CREATED: 'PAYMENT_CREATED',
  CHARGE_CANCELED: 'CHARGE_CANCELED',
} as const

export type AuditAction =
  (typeof AUDIT_ACTIONS)[keyof typeof AUDIT_ACTIONS]
